workflows:
  build_apk:
    name: Build APK
    scripts:
      - name: Install dependencies
        script: |
          if [ -f yarn.lock ]; then
            yarn install
          else
            npm install
          fi
      - name: Install EAS CLI
        script: npm install -g eas-cli
      - name: Build APK
        script: eas build -p android
    artifacts:
      - '*.apk'
