workflows:
  managed_workflow:
    name: Build Managed Workflow
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: eas build -p android
    artifacts:
      - '*.apk'
